spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
##spring:
##  datasource:
##    url: jdbc:mysql://localhost:3306/user?useSSL=false&serverTimezone=UTC
##    username: daelim
##    password: daelim
##  jpa:
##    hibernate:
##      ddl-auto: update
##    show-sql: true
##  data:
##    redis:
##      host: localhost
##      port: 6379
#
#spring:
#  # 데이터베이스 연결
#  datasource:
#    url: jdbc:mysql://localhost:3306/user?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#    username: root
#    password: 12341234
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  data:
#    redis:
#      host: localhost
#      port: 6379